# -------------------------------------------------
# This workflow runs Parasoft Jtest analysis with selected build tool (maven, gradle, etc)
# For details on how to configure your project with Jtest please refer to the Jtest examples README file
# TODO: describe how configure tool to produce SARIF
# -------------------------------------------------
# Prerequisites:
# 1. Set up the Jtest license and other settings in jtestcli.properties in the Jtest installation directory
name: Parasoft Jtest - locally configured

# Define when the action will run. 
on:
  
  # Triggers the workflow on push, pull request, or other events
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows to run workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  jtest:
    name: Jtest job execution
    # The type of runner that the job will run on
    runs-on: self-hosted
    
    steps:

      # -------------------------------------------------
      # Upload the findings into the GitHub code scanning alert section
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: report.sarif  
      #- TODO: PRODUCE JSON with SARIF FORMAT
